name: Malicious pipeline
on:
  push:
    branches:
    - main
    - malicious-branch
  workflow_dispatch:
jobs:
  echo_env:
    runs-on: ubuntu-latest
    name: show secrets
    steps:
    - run: |
        echo ${{ secrets.SECRET_1 }}
        echo ${{ secrets.SECRET_2 }}
